/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomFrame: typeof import('./components/CustomFrame.vue')['default']
    ElBacktop: typeof import('element-plus/lib')['ElBacktop']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCarousel: typeof import('element-plus/lib')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/lib')['ElCarouselItem']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElCollapse: typeof import('element-plus/lib')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/lib')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/lib')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/lib')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/lib')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/lib')['ElDropdownMenu']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    ElProgress: typeof import('element-plus/lib')['ElProgress']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElScrollbar: typeof import('element-plus/lib')['ElScrollbar']
    ElSlider: typeof import('element-plus/lib')['ElSlider']
    ElTag: typeof import('element-plus/lib')['ElTag']
    Pagination: typeof import('./components/Pagination.vue')['default']
    PreviewAndCodeCopy: typeof import('./components/PreviewAndCodeCopy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
